test3

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -144,20 +144,25 @@ jobs:
     - name: Get the Latest Task Definition
       id: get-task-def
       run: |
-        TASK_FAMILY=$(aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE \
-          --query "services[0].taskDefinition" --output text | cut -d'/' -f2)
-        echo "TASK_FAMILY=$TASK_FAMILY" >> $GITHUB_ENV
+        TASK_ARN=$(aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE \
+          --query "services[0].taskDefinition" --output text)
+        
+        if [ -z "$TASK_ARN" ]; then
+          echo "Error: No task definition found for the ECS service."
+          exit 1
+        fi
 
+        TASK_FAMILY=$(echo $TASK_ARN | cut -d'/' -f2)
+        echo "TASK_FAMILY=$TASK_FAMILY" >> $GITHUB_ENV
     - name: Register New Task Definition with Updated Image
       id: register-task-def
       run: |
-        aws ecs describe-task-definition --task-definition $TASK_FAMILY \
-          --query taskDefinition | jq 'del(.taskDefinitionArn, .requiresAttributes, .compatibilities, .revision, .status, .registeredAt, .registeredBy) | 
-          (.containerDefinitions[0].image = env.IMAGE_URI)' > task-def.json
-
-        NEW_TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://task-def.json --query "taskDefinition.taskDefinitionArn" --output text)
-        echo "NEW_TASK_ARN=$NEW_TASK_ARN" >> $GITHUB_ENV
-
+          aws ecs describe-task-definition --task-definition $TASK_FAMILY \
+            --query taskDefinition | jq 'del(.taskDefinitionArn, .requiresAttributes, .compatibilities, .revision, .status, .registeredAt, .registeredBy) | 
+            (.containerDefinitions[0].image = env.IMAGE_URI)' > task-def.json
+  
+          NEW_TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://task-def.json --query "taskDefinition.taskDefinitionArn" --output text)
+          echo "NEW_TASK_ARN=$NEW_TASK_ARN" >> $GITHUB_ENV    
     - name: Deploy New Task Definition to ECS Service
       run: |
         aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $NEW_TASK_ARN --force-new-deployment
